apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: golang-test-service
  namespace: aletheia-test
  labels:
    app: golang-test-service
    component: test-service
spec:
  selector:
    matchLabels:
      app: golang-test-service
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
