apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-called-config
  labels:
    app: ms-called
    component: callee
data:
  config.yaml: |
    server:
      port: "8080"

    downstream:
      url: "http://localhost:8080/api/v1/called"
      timeout: 30s
