apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-call-config
  labels:
    app: ms-call
    component: caller
data:
  config.yaml: |
    server:
      port: "8080"

    downstream:
      url: "http://ms-called:8080/api/v1/called"
      timeout: 30s
