apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-test-service
  namespace: aletheia-test
  labels:
    app: java-test-service
    service: test
    language: java
spec:
  selector:
    matchLabels:
      app: java-test-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
