apiVersion: v1
kind: Service
metadata:
  name: java-test-service
  namespace: aletheia-test
  labels:
    app: java-test-service
    service: test
    language: java
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: java-test-service
